grammatical correction
tdunning/t-digest pull request #186
Opened 2022-01-29 11:55 UTC by njmsaikat

2022-01-29 20:18 UTC, tdunning requested changes
I think that I agree with about 2/3 of these. Some are obvious improvements (like correting the speling of auxillary), but I strongly disagree some.

Can we come to consensus on these?

2022-01-29 20:18 UTC, tdunning commented on README.md
> +A new data structure for accurate online accumulation of rank-based statistics such as quantiles
this is a matter of opinion. Different folks prefer different ways.

Happy to move to your form

2022-01-29 20:18 UTC, tdunning commented on README.md
> +* works on double-precision floating points as well as integers.
This usage of floating point as a noun by analogy with integers is interesting. My feeling, however, is that floating point here is an adjective, not a noun (an elision of "floating point number", contrast with "integer number") and thus should not be made plural.

2022-01-29 20:18 UTC, tdunning commented on README.md
> +* provides part per million accuracies for extreme quantiles and typically <1000 ppm accuracy for middle quantiles
This should not be made plural.

2022-01-29 20:18 UTC, tdunning commented on README.md
> +Lots have happened in t-digest lately. Most recently, with the help of people
The standard idiom in American English is "lots has happened". Let's stick with that.

2022-01-29 20:18 UTC, tdunning commented on README.md
> +The basic gist of other recent changes is that the core algorithms have been
Good catch on this one. There didn't use to be more than one change!

2022-01-29 20:18 UTC, tdunning commented on README.md
> + * docs - the main paper and auxiliary proofs live here
Thank you for catching this.

2022-01-29 20:18 UTC, tdunning commented on README.md
> + * docs - the main paper and auxiliary proofs live here
Thank you for catching this.

2022-01-29 20:18 UTC, tdunning commented on README.md
> + * quality - this is the code that generates and analyzes accuracy of information
I don't agree with this. the code analyzes information about accuracy. The information is the output of the test, not hte information contained in the t-digest.

2022-01-29 20:18 UTC, tdunning commented on README.md
> + * docs - the main paper and auxiliary proofs live here
Thank you for catching this.

2022-01-29 20:18 UTC, tdunning commented on README.md
> +These scale functions now have associated proof that they all
I think that there are multiple proofs (one each for each scale function)

What is the rationale for the singular here? I may be off base.

2022-01-30 05:24 UTC, njmsaikat commented
made requested changes https://github.com/tdunning/t-digest/pull/187

2022-01-30 07:44 UTC, closed without merging